name: rclone_release

on: 
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name' 
        required: true
        default: 'v0.1.0'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        repository: gaoyb7/rclone
        ref: feat-115-drive

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v3
      with:
        version: latest
        args: release --snapshot --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        tag_name: ${{ inputs.tag_name }}-rclone
        token: ${{ secrets.GITHUB_TOKEN }}
        files: dist/*.tar.gz
